<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arm_control_cpp</name>
  <version>0.0.0</version>
  <description>
    This package is the core logical flow for the Apple Picking system. See README for instruction.
    This package is the sole controller of moveit, no other package may command moveit.
  </description>
  <maintainer email="devanneil2004@gmail.com">Devan Neil</maintainer>
  <license>MIT</license>
  <url type="website">https://github.com/devanneil/AutomaticAppleHarvesterCOBOT</url>

  <depend>apple_interfaces</depend>

  <depend>rclcpp</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_core</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_visual_tools</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
