# Goal
uint8 order
uint8 APPLE_SCAN=0
uint8 QR_SCAN=1
uint32 RADIUS = 250
string qr_message
---
# Result
string status
---
# Feedback
bool success
geometry_msgs/PoseStamped[] apples
geometry_msgs/PoseStamped qr_pose
